guegue/transmunic

requirements.txt
=> Revert "Bump gunicorn from 19.9.0 to 20.0.0"

core/templates/consolidado_municipal.html, core/templates/home.html
En la portada, para Origen de los Ingresos, Destino de los gastos y Destino de la inversión, mostrar la informacion en porcentaje y en millones de cordobas
=> Tarea 3086

core/charts/bubble_oim.py, core/templates/consolidado_municipal.html
eliminando libreria sin utilidad 
eliminando **tercer nivel** de grafico de burbuja
=> Tarea 3085

core/static/css/own.css, core/static/js/own.js, core/templates/_base.html, core/templates/consolidado_municipal.html, core/templates/home.html
1. Cambiar los tipos de letra de los cuadros celestes que muestan el presupuesto de ingreso total y el de gastos. Usar mismo tipo de letra que usa el detalle
2. hacer un poco mas grande el tamanho del asignado/ejecutado en el listado de inversiones
3. Mostrar el asignado/ejecutado en millones de cordobas cuando se da en Ver mas
4. Cambiar el ver mas por ver menos cuando estan desplegados los iconos
=> Tarea 3091

core/views.py
Agregando order by a consulta para obtener principales categorías de inversion y categorías secundarias de inversion
=> Aplicando Order By a Categorias de Inversion

core/charts/bubble_ogm.py
eliminando tercer nivel de grafico de burbuja en destino del gasto municipal
=> eliminando tercer nivel de grafico de burbuja

requirements.txt
also, no need for debug toolbar
=> fix pixelfields smart selects

core/static/css/own.css, core/templates/_indicator.html, core/templates/ogm_chart.html, core/templates/oim_chart.html
1. Carmbiar titulo de la seccion
2. Bajar resumen de ingresos y ejecucion debajo del titular "Ingresos presupuesto cierre"
3. Agregar fuente a las diferentes tablas que indiquen "Fuente: Elaboración propia a partir de transmuni.gob.ni "
4. Agregar titulo a tabla de rubtos
5. Renombrar COrdobas por MIllones de cordobas
6. Rankin de recaudacion indicar a que periodo y anio corresponde la informacion
7. Mover Modificaciones del presupuesto arriba de informacion historica
=> Tarea 3109

core/static/css/own.css, core/templates/_base.html, core/templates/ogm_chart.html
Cambiar tipo de letra en cifras, utilizar **'Roboto'** o sans-serif para todas las tablas.
=> Tarea 3106

core/templates/inversionpiechart.html
identando codigo html de inversionpiechart.html
=> inversionpiechart

core/importer.py, core/tools.py
actualiza ingreso de ser necesario y mejor manejo de numeros
=> repara importador

core/charts/inversion.py
See "Interaction with default ordering or order_by()" in Django 1.11 docs
=> order_by para quitar orden de query

core/static/css/pma.css
=> ajuste de color en slider

core/templates/base.html
validando si esta es la actual url de importador no agrege jquery al html a renderizar
=> Fix de radio buttons en importado

core/charts/ogm.py, core/charts/oim.py, core/charts/personal.py, core/importer.py, core/tools.py
previene Variable doesn't exist, en math filters del template (solo para OIM en este caso)
=> adds value as zero if it doens't exist

core/charts/personal.py
requiere 'mapping' con datos definido, para 'gpersonal'
=> hace uso de mapping en Anio para gpersonal

core/charts/oim.py, core/templates/oim_chart.html, core/templates/ranking_municipio.html
Refactorizando codigo de oim.py
Creacion de grafico municipal y por categoria para origen de los ingresos
Eliminando codigo html de timeline
=> Ranking oim municipal

core/charts/bubble_oim.py, core/charts/oim.py
Excluyendo saldo de caja de ingresos por rankin y tipos de ingresos en resumen municipal
=> Validando 2014

core/admin.py
Agregando periodo y anio en listado de ingresos en admin
=> Agregando periodo y anio en listado de ingresos en admin

core/forms.py, core/importer.py
=> Limitando select de municipio (interfaz de renglón ingreso)

core/charts/oim.py
- Divisison entre la poblacion total por categoria
- Restringiendo solamente a cuenta de recaudacion
=> Corrigiendo formular del rankin global

core/charts/oim.py
Excluyendo saldo de caja de tabla de historico anual
=> excluyendo saldo de caja de total por anio

core/views.py
- Validando si existe year
- Quitando codigo de inversion por fuente de financiamiento de portada
=> Quitando inversion minima por sector de portada

core/charts/oim.py
Excluyendo saldo de caja de calculo de ingresos
=> Excluyendo saldo de caja de calculo anual de ingresos

core/templates/oim_chart.html
Ahora bloque de rankin de managua diferente al de otros municipios
Agregando subtitulo Córdobas corrientes por habitante en base a ingresos ejecutados
=> Ajustes diseno

core/charts/oim.py, core/static/css/own.css, core/templates/oim_chart.html
- Reordenando rankin para managua
- ELiminando height de grafico de barra de rankin
=> reordenando cuando municipio es managua para el rankin de racaudacion

core/models.py, core/templates/consolidado_municipal.html, core/templates/home.html
ordenando gastos en admin por campo orden
Cambiando titulo del resumen municipal
=> Ajustes varios

core/templates/home.html, core/views.py
Ordenar los datos por **Asignados** si el periodo del año es Inicial sino por **Ejecutado**
=> Portada Area inversion

core/static/js/own.js
=> agregando acento a mas en javascript

core/charts/ogm.py, core/charts/oim.py
Primeramente agregue a los values de cada consulta ORM el campo order, para luego utilizar el metodo sorted y organizar por el campo orden
=> Portada origen destino ordenar por campo orden

core/static/js/pma.js, core/templates/_base.html, core/templates/_indicator.html
Continuacion de PR 102 https://github.com/guegue/transmunic/pull/102
=> Menu principal filtros continuacion

core/templates/_indicator.html, core/templates/oim_chart.html
- Ajustes en titulos de tablas de modificaciones , rankin e historico de ingresos
=> Ajustes titulos tablas de ingresos

core/templates/municipal-triangle.html
agregando span.municipio-data 
validando tamaño del numero de la posicion >= 100 atributo left sera 16.3%
=> correccion enmaquedato de detalles municipio globo posicion, grafico de triangulo

core/templates/expenses.html
Corrigiendo titulos de gastos de funcionamiento
=> Corrigiendo titulos de gastos de funcionamiento

core/templates/variance_analysis.html
validando si se encuenta en la url /core/ep sin municipio solo renderice una tabla caso contrario no existe bloque de ranking
=> ocultar graficos en url de ejecucion de presupuesto solo mostrar tabla de ingreso y gasto

core/charts/funcionamiento.py, core/templates/_indicator.html, core/templates/expenses.html
aplica para los demas indicadores pero debe enviarse en el context las siguientes key sin valores None **asignado_percent** y **ejecutado_percent**
=> Porcentaje de ejecutado y asigando summary para gf

core/importer.py, core/templates/renglon_ingreso.html
- garantizar que guarda y valida los datos ingresados
- validar que el anio que se registre sea >= 2018
- filtrar los tiposingresos por el campo "nuevo_catalogo" 
- asegurarse de enviar de mensaje de "guardado exitosamente" despues de guardar
- permitir datos solamente con decimales
=> Mejorando formulario renglon ingreso

core/templates/renglon_gasto.html, core/templates/renglon_ingreso.html
- cambiando de posicion boton de submit
- cambiando label de boton submit "Submit" => "Registrar Municipio"
- mantener los paneles colapsables por defecto cerrados
=> Mejorando formularios renglones

core/templates/transferencias.html, core/tools.py, core/views.py
Observación si la diferencia de corriente y capital es muy grande chartit no grafica la barra. ejemplo
año 2015
corriente: 10,000
capital:     100,000
chartit en el año 2015 solo mostrara *capital*
=> Creando grafico dos barras municipio

core/charts/aci.py, core/charts/ago.py, core/charts/funcionamiento.py, core/charts/inversion.py, core/charts/ogm.py, core/charts/oim.py, core/charts/personal.py, core/static/js/map-ni-drilldown.js, core/templates/_base.html, core/templates/ep.html, core/templates/expenses.html, core/templates/ogm_chart.html, core/templates/oim_chart.html, core/templates/variance_analysis.html, core/tools.py
- Corrección en Mapa se mostraba en el tooltip de cada departamento un encabezado **Serie 1**
- Eliminando excesivo Alto de grafico de columnas para OIM
- Corrección de menu de navegación al selecionar una opcion con nombre de gran longitud dañaba el diseño
- Corrección de formado de decimales para graficos de Barra ó Columnas en los indicadores
=> Improving esthetic site

core/templates/ogm_chart.html, core/templates/oim_chart.html, core/templates/tasa_transferencias.html, core/templates/transferencias.html, core/tools.py, core/views.py
mostrando el periodo y partido politico en la tabla de segundo municipio
reemplazando clase => clasificacion
ordenando alfabeticamente los municipios de mayor/menor tasa de crecimiento
=> Reparando observaciones

core/charts/inversion.py, core/charts/ogm.py, core/templates/expenses.html, core/templates/inversionpiechart.html, core/templates/ogm_chart.html, core/tools.py
=> Revert "Reparando observaciones(Sin Clasificar donde el nombre del rubro es None para 2016 OGM, corregir error de areas para 2016 inversion)"

core/charts/inversion.py, core/charts/ogm.py, core/templates/expenses.html, core/templates/inversionpiechart.html, core/templates/ogm_chart.html, core/tools.py
Este PR es el correcto, no el  [https://github.com/guegue/transmunic/pull/243](url)
=> Reparando observaciones(Sin Clasificar donde el nombre del rubro es None para 2016 OGM, corregir error de areas para 2016 inversion) 

core/charts/oim.py
Nota replicar para indicador OGM
=> Ordenando diccionario de rubros para sección de información histórica
